### PR TITLE
Ticked to version 1.2.0

### PR DESCRIPTION
**Pull request by jessemapel**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jessemapel** [comment]
@conda-forge-admin, please rerender

**Comment by jessemapel** [comment]
@jlaura This looks like an issue with the OSX Azure pipeline. I'm not sure what to do about this.

**Comment by jlaura** [comment]
@jessemapel I just saw this on the next PR. I reran that job. I'll rerun this job if that is the fix. Otherwise, I'll post on conda-forge gitter to see if other packages are having this issue.

**Comment by jlaura** [comment]
Rerun was successful.

**Pull request merged**
